[package]
name = "hgvs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
enum-map = "2.4.2"
flate2 = "1.0.25"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
nom = "7.1.3"
postgres = "0.19.4"
pretty_assertions = "1.3.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
