[package]
name = "hgvs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
base16ct = "0.2.0"
bio = "1.1.0"
chrono = "0.4.23"
enum-map = "2.4.2"
flate2 = "1.0.25"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
log = "0.4.17"
md-5 = "0.10.5"
nom = "7.1.3"
phf = { version = "0.11.1", features = ["macros"] }
postgres = { version = "0.19.4", features = ["with-chrono-0_4"] }
pretty_assertions = "1.3.0"
quick_cache = "0.2.2"
regex = "1.7.1"
seqrepo = { git = "https://github.com/bihealth/seqrepo-rs.git", branch = "27-whole-fasta-sequences-are-read" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"

[dev-dependencies]
csv = "1.2.0"
env_logger = "0.10.0"
rstest = "0.16.0"
serde = { version = "1.0.152", features = ["derive"] }
test-log = "0.2.11"
